services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kohkau11999
      - POSTGRES_DB=test_case_db_1
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./app:/app
    command: bash -c "sed -i 's|sqlalchemy.url = postgresql://postgres:Kohkau11999@localhost:5432/test_case_db_1|sqlalchemy.url = postgresql://postgres:Kohkau11999@db:5432/test_case_db_1|g' alembic.ini && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kohkau11999
      - POSTGRES_DB=test_case_db_1
    restart: always

volumes:
  postgres_data: